### ISSUE TITLE
Agora vai estudar um pouco de git para comećar a usar os branchs para develop e test

### ISSUE THREAD

**Issue by apinheiro99** [Pinheirops/Exercicio-1.Nacionalidade#1]
Ja assistiu os videos que eu te mandei?

Usa o gitKrakenj para entender melhor

**Comment by Pinheirops** [comment]
Vou assistir ainda, pra ir usando o git enquanto faço o curso de Js, ai ja prático duas coisas, eu não sei o que é gitKrakenj não, mas vou ver os videozinhos pra saber.

**Comment by Pinheirops** [comment]
Aaa ta, entendi, o Gitkraken, a extensão que mostra cada branch, alteração, etc...
Vou usar, valeeeu
